import type { PlanDef } from "./types";

export const PLANS: PlanDef[] = [
  {
    id: "free",
    name: "Free",
    priceMonthly: 0,
    description: "Try NextGen AI with no commitment.",
    highlights: ["10 AI generations / mo", "1 GB storage", "Community templates"],
    features: [
      "10 AI generations per month",
      "Up to 3 projects",
      "1 GB storage",
      "Community templates",
      "Built-in IDE & live preview",
      "Public projects",
    ],
    aiGenerationsPerMonth: 10,
    storageGB: 1,
    maxProjects: 3,
    prioritySupport: false,
    cta: "Start free",
  },
  {
    id: "pro",
    name: "Pro",
    priceMonthly: 19,
    description: "For makers shipping AI-built apps weekly.",
    highlights: ["500 AI generations / mo", "20 GB storage", "Premium templates"],
    features: [
      "500 AI generations per month",
      "Unlimited projects",
      "20 GB storage",
      "Premium templates",
      "Faster generation queue",
      "Private projects",
      "GitHub & ZIP export",
    ],
    aiGenerationsPerMonth: 500,
    storageGB: 20,
    maxProjects: 1000,
    prioritySupport: false,
    popular: true,
    cta: "Upgrade to Pro",
  },
  {
    id: "premium",
    name: "Premium",
    priceMonthly: 49,
    description: "Advanced AI tooling for power users & small teams.",
    highlights: ["2,000 AI generations / mo", "100 GB storage", "Team workspace"],
    features: [
      "2,000 AI generations per month",
      "Team collaboration",
      "100 GB storage",
      "Advanced AI: refactor, a11y, perf",
      "Priority generation",
      "Custom domains",
      "Priority email support",
    ],
    aiGenerationsPerMonth: 2000,
    storageGB: 100,
    maxProjects: 10000,
    prioritySupport: true,
    cta: "Go Premium",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    priceMonthly: 0,
    description: "Custom limits, SSO, white-label, and SLAs.",
    highlights: ["Unlimited AI", "Unlimited storage", "Dedicated support"],
    features: [
      "Unlimited AI generations",
      "Unlimited projects & storage",
      "SSO / SAML",
      "White-label deployments",
      "Audit logs & compliance exports",
      "Dedicated account manager",
      "99.9% uptime SLA",
    ],
    aiGenerationsPerMonth: 1_000_000,
    storageGB: 10_000,
    maxProjects: 1_000_000,
    prioritySupport: true,
    cta: "Contact sales",
  },
];

export function getPlan(id: string): PlanDef {
  return PLANS.find((p) => p.id === id) ?? PLANS[0];
}
